[[main]]
none = "none"

[[main]]
name = "About"
pageRef = "about"
weight = 10

[[main]]
name = "Resume"
url = "https://github.com/DJKero/djkero.github.io/blob/master/assets/resume/resume.pdf"
weight = 20

[[main]]
name = "Projects"
pageRef = "projects"
weight = 30

[[footer]]
none = "none"
